[package]
name = "s4mp-parse"
description = "Parsing orchestration for S4MP"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
s4mp-core = { workspace = true }
s4mp-ir = { workspace = true }
s4mp-plugin-api = { workspace = true }
s4mp-plugin-host = { workspace = true }
s4mp-store = { workspace = true }
