[package]
name = "s4mp-conformance"
description = "Conformance tests for S4MP plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
s4mp-plugin-api = { workspace = true }
s4mp-plugin-sdk = { workspace = true }

[dev-dependencies]
s4mp-store = { workspace = true }
